# sudo apt-get install gcc-avr avr-libc avrdude arduino arduino-mk
# make upload
BOARD_TAG    = uno
AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
include /usr/share/arduino/Arduino.mk